### ISSUE TITLE
issue with System.ValueTuple dependency in version 2.12

### ISSUE THREAD

**Issue by MovGP0** [DuendeArchive/IdentityModel.PCL#71]
When calling the `DiscoveryClient` from an `.NET Framework 4.6.1` project with `System.ValueTuple 4.3.1` referenced, I get an exception: 

**Exception**
```
=== Pre-bind state information ===
LOG: DisplayName = System.ValueTuple, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Users/johann/AppData/Local/Azure.Functions.Cli/1.0.4/
LOG: Initial PrivatePath = NULL
Calling assembly : IdentityModel, Version=2.12.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Users\johann\AppData\Local\Azure.Functions.Cli\1.0.4\func.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
```

**Stack Trace**
```
   at IdentityModel.Client.DiscoveryClient..ctor(String authority, HttpMessageHandler innerHandler)
   at IdentityModel.Client.DiscoveryClient.<GetAsync>d__1.MoveNext()
```

**Comment by MovGP0** [comment]
this applies to version 2 of this library and not version 1. reopened the ticket here: 

https://github.com/IdentityModel/IdentityModel2/issues/64
